Repository NPCreno/get-it-done-BE, pull requests merged in 2025-07, with the labels that each got.

#20 feat: Add project management endpoints and enhance task features
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: Review effort 3/5

#21 Improve Error Handling and Streak Logic
  src/task/task.service.ts
  src/task/taskGenerator.service.ts
Labels: Review effort 4/5

#23 added dockerfile
  .dockerignore
  .env.example
  DOCKER.md
  Dockerfile
  docker-compose.yml
Labels: Review effort 2/5, Possible security concern
